### ISSUE TITLE
cant use discord rn

### ISSUE THREAD

**Issue by DomTheNoobCoder** [LEVIXDDLMAO/Sonic.EXE_3.0-SC#1]
### What is your question?

 are y'all restoring the songs or just making the source

**Comment by MemeHoovy** [comment]
> ### What is your question?
> are y'all restoring the songs or just making the source

both

**Comment by LEVIXDDLMAO** [comment]
both, but this is broken as of now

**Comment by MemeHoovy** [comment]
> both, but this is broken as of now

I literally just said that

**Comment by LEVIXDDLMAO** [comment]
sorry

**Comment by MemeHoovy** [comment]
> sorry

nah it's fine

**Comment by LEVIXDDLMAO** [comment]
:D
